- build.gradle
- src/main/java/classfit/example/classfit/ClassfitApplication.java
- src/main/java/classfit/example/classfit/common/ApiResponse.java
- src/main/java/classfit/example/classfit/common/BaseEntity.java
- src/main/java/classfit/example/classfit/common/ResultType.java
- src/main/java/classfit/example/classfit/config/SwaggerConfig.java
- src/main/java/classfit/example/classfit/config/SwaggerController.java
- src/main/java/classfit/example/classfit/config/WebConfig.java
- src/main/java/classfit/example/classfit/exception/ClassfitException.java
- src/main/java/classfit/example/classfit/exception/ClassfitExceptionControllerAdivce.java
> [Feat] 전반적인 유틸리티 구현 #3

- src/main/java/classfit/example/classfit/common/AttendanceStatus.java
- src/main/java/classfit/example/classfit/common/Gender.java
- src/main/java/classfit/example/classfit/common/LoginType.java
- src/main/java/classfit/example/classfit/common/MemberStatus.java
- src/main/java/classfit/example/classfit/domain/Attendance.java
- src/main/java/classfit/example/classfit/domain/ClassStudent.java
- src/main/java/classfit/example/classfit/domain/MainClass.java
- src/main/java/classfit/example/classfit/domain/Member.java
- src/main/java/classfit/example/classfit/domain/Student.java
- src/main/java/classfit/example/classfit/domain/SubClass.java
도메인에 맞는 ENUM 타입과 도메인 생성 후, 테이블 관계 정의
-----------------------
※ 코멘트 달아주시면 감사하겠습니다 : )
> [feat] 엔티티 관계 정의 및 필드 설정 #11

- src/main/java/classfit/example/classfit/category/controller/ClassInfoController.java
- src/main/java/classfit/example/classfit/category/dto/response/ClassInfoResponse.java
- src/main/java/classfit/example/classfit/category/dto/response/SubClassResponse.java
- src/main/java/classfit/example/classfit/category/repository/MainClassRespository.java
- src/main/java/classfit/example/classfit/category/service/ClassInfoService.java
> [Feat] 클래스 정보 조회 API

- src/main/java/classfit/example/classfit/category/repository/SubClassRepository.java
- src/main/java/classfit/example/classfit/class_student/repository/ClassStudentRepository.java
- src/main/java/classfit/example/classfit/common/ApiResponse.java
- src/main/java/classfit/example/classfit/domain/ClassStudent.java
- src/main/java/classfit/example/classfit/domain/Student.java
- src/main/java/classfit/example/classfit/domain/SubClass.java
- src/main/java/classfit/example/classfit/student/controller/StudentControllerImpl.java
- src/main/java/classfit/example/classfit/student/dto/request/StudentRequest.java
- src/main/java/classfit/example/classfit/student/dto/request/UpdateStudentRequest.java
- src/main/java/classfit/example/classfit/student/dto/response/StudentResponse.java
- src/main/java/classfit/example/classfit/student/repository/StudentRepository.java
- src/main/java/classfit/example/classfit/student/service/StudentService.java
> [feat] 학생 정보 API 

- src/main/java/classfit/example/classfit/category/controller/MainClassController.java
- src/main/java/classfit/example/classfit/category/dto/response/AllMainClassResponse.java
- src/main/java/classfit/example/classfit/category/service/MainClassService.java
> [feat] 메인 클래스 조회기능 추가

- src/main/java/classfit/example/classfit/student/controller/StudentControllerImpl.java
- src/main/java/classfit/example/classfit/student/dto/response/StudentInfoResponse.java
- src/main/java/classfit/example/classfit/student/repository/StudentRepository.java
- src/main/java/classfit/example/classfit/student/service/StudentService.java
> [feat] 학생 이름 검색 API

- build.gradle
- src/main/java/classfit/example/classfit/domain/Member.java
- src/main/java/classfit/example/classfit/domain/Student.java
- src/main/java/classfit/example/classfit/sms/controller/SendMessageController.java
- src/main/java/classfit/example/classfit/sms/dto/SendRequest.java
- src/main/java/classfit/example/classfit/sms/service/SmsService.java
- src/main/java/classfit/example/classfit/student/StudentRepository.java
아직 student에 문자 받았는지 여부 저장 안됨 중간 이후 리팩토링 필요
> [Feat] 단체문자 API

- build.gradle
- src/main/java/classfit/example/classfit/attendance/controller/AttendanceExportController.java
- src/main/java/classfit/example/classfit/attendance/service/AttendanceExportService.java
- src/main/java/classfit/example/classfit/attendance/service/AttendanceService.java
- 엑셀파일 다운로드 로직 변경
- 실제 파일 다운로드에서 데이터 응답으로 변경
- 이름 오름차순 정렬
|기능|스크린샷|
|---|---|
|**수정 전**|<img width="818" alt="image" src="https://github.com/user-attachments/assets/9562af4d-bab8-4cc9-b9f9-f36b3f55cd3a">|
|**수정 후**|<img width="583" alt="image" src="https://github.com/user-attachments/assets/71fd3973-7a4a-4960-be32-c6583d7d0d79">|
Resolved: #9
> [Fix] 엑셀 다운로드 로직 변경 #9

- src/main/java/classfit/example/classfit/student/service/StudentService.java
- 학생 등록 시 출결 데이터 자동 생성
- 기존에 출결 조회 API는 있었지만, 학생 등록 시 출결 데이터가 생성되지 않아 조회할 데이터가 없어 빈칸으로 조회되는 문제 발생함
- 학생이 특정 클래스에 등록될 때, 해당 주와 향후 2주간의 출결 데이터를 자동으로 생성
- 기본 PRESENT로 출결 상태로 생성됨
- 예를 들어, 한 학생이 여러 클래스에 소속되어 있을 경우, 전체 학생의 출결을 조회할 때 해당 학생의 각 클래스별 출결 정보가 모두 조회됨
- 학생이 수요일에 등록되면, 이전의 월요일과 화요일에도 자동으로 'PRESENT' 상태로 출결 데이터가 생성됨
- 출결 상태가 PRESENT, ABSENT, LATE 밖에 없음
- 기획팀과 상의해야할 것 같음
|기능|스크린샷|
|---|---|
|**출결 조회**|<img width="573" alt="image" src="https://github.com/user-attachments/assets/084c99b6-e298-4590-8416-2d4e95f9537b">|
|**엑셀 다운로드**|<img width="558" alt="image" src="https://github.com/user-attachments/assets/10843312-06f0-49aa-8e31-f6f5dd133145">
Resolved: #45
> [Feat] 출결 데이터 생성 

- build.gradle
- src/main/java/classfit/example/classfit/common/validation/EnumValidator.java
- src/main/java/classfit/example/classfit/common/validation/EnumValue.java
- src/main/java/classfit/example/classfit/common/validation/NotBlankEnumValidator.java
- src/main/java/classfit/example/classfit/common/validation/NotBlankNullable.java
- src/main/java/classfit/example/classfit/common/validation/NotBlankNullableValidator.java
- src/main/java/classfit/example/classfit/exception/ClassfitExceptionControllerAdivce.java
- src/main/java/classfit/example/classfit/student/dto/request/StudentRequest.java
- src/main/java/classfit/example/classfit/student/dto/request/StudentUpdateRequest.java
- src/main/java/classfit/example/classfit/student/service/StudentService.java
* 유효성 검증이 이뤄지지 않은 문제 발견
* Enum 타입의 경우, 유효성 검증 어노테이션 적용시, 역직렬화 과정에서 예외 발생 확인
* **Enum 타입의 유효성 검증 커스텀 어노테이션 생성**
1. MALE, FEMALE (대소문자 구분 X) 검증하는 로직 추가
* **String 타입의 유효성 검증 커스텀 어노테이션 생성**
1. Null은 허용하지만, Blank는 허용하지 않도록 하는 로직 추가
* Enum 타입의 유효성 검증하는 커스텀 어노테이션 적용
* validation 라이브러리 추가
* RestControllerAdvice 클래스의 예외 처리 메시지 구조 변경
* String 타입의 유효성 검증 커스텀 어노테이션 적용
* HttpMessageNotReadableException 예외처리
> [Fix] Request DTO 유효성 검증 해결

- src/main/java/classfit/example/classfit/mail/controller/EmailAuthController.java
- 유효성 검사를 위한 DTO 생성으로 @GetMapping -> @PostMapping 수정
---
---
> [Refactor] HTTP 메서드 수정

- src/main/java/classfit/example/classfit/academy/domain/Academy.java
- src/main/java/classfit/example/classfit/member/domain/Gender.java
- src/main/java/classfit/example/classfit/member/domain/LoginType.java
- src/main/java/classfit/example/classfit/member/domain/Member.java
- src/main/java/classfit/example/classfit/student/domain/Gender.java
- src/main/java/classfit/example/classfit/student/domain/Student.java
- src/main/java/classfit/example/classfit/student/dto/request/StudentRequest.java
- src/main/java/classfit/example/classfit/student/dto/request/StudentUpdateRequest.java
- src/main/java/classfit/example/classfit/student/dto/response/StudentInfoResponse.java
- src/main/java/classfit/example/classfit/student/service/StudentService.java
- [학원 - 멤버], 1:N 관계로 학원 Entity 추가 
- BaseEntity로 관리
- 이름, 이메일, 휴대폰 번호, 비밀번호 필드로 수정
---
> [Feat] 학원 Entity 추가 및 멤버 Entity 필드 수정

- src/main/java/classfit/example/classfit/attendance/domain/Attendance.java
- src/main/java/classfit/example/classfit/attendance/dto/response/AttendanceResponse.java
- src/main/java/classfit/example/classfit/attendance/service/AttendanceExportService.java
- src/main/java/classfit/example/classfit/attendance/service/AttendanceSchedulingService.java
- src/main/java/classfit/example/classfit/attendance/service/AttendanceService.java
- src/main/java/classfit/example/classfit/attendance/service/AttendanceUpdateService.java
- src/main/java/classfit/example/classfit/student/service/StudentService.java
- src/test/java/classfit/example/classfit/attendance/service/AttendanceSchedulingServiceTest.java
- 스케쥴링 시 월요일부터 데이터를 생성해야 하는데 일요일부터 생기는 오류 해결
- 월요일부터 데이터 생성하기
- 테스트 코드 작성
- 출결 데이터 조회 시 요일 정보 추가(월요일:0 ~일요일:6)
Resolved: #82
> [Fix] 출결 데이터 생성

- src/main/java/classfit/example/classfit/academy/controller/AcademyController.java
- src/main/java/classfit/example/classfit/academy/domain/Academy.java
- src/main/java/classfit/example/classfit/academy/dto/request/AcademyRequest.java
- src/main/java/classfit/example/classfit/academy/dto/response/AcademyResponse.java
- src/main/java/classfit/example/classfit/academy/repository/AcademyRepository.java
- src/main/java/classfit/example/classfit/academy/service/AcademyService.java
- src/main/java/classfit/example/classfit/config/SecurityConfig.java
- src/main/java/classfit/example/classfit/mail/service/EmailAuthService.java
- src/main/java/classfit/example/classfit/member/controller/MemberController.java
- src/main/java/classfit/example/classfit/member/domain/Member.java
- src/main/java/classfit/example/classfit/member/repository/MemberRepository.java
- src/main/java/classfit/example/classfit/member/service/MemberService.java
- src/main/java/classfit/example/classfit/util/CodeUtil.java
---
----
※ 회원이 기존 학원 합류하는 API는 추후에 구현하도록 하겠습니다.
> [Feat] 학원 등록 및 학원 코드 생성 API

- src/main/java/classfit/example/classfit/attendance/controller/AttendanceStatisticsController.java
- src/main/java/classfit/example/classfit/attendance/dto/response/StatisticsMemberResponse.java
- src/main/java/classfit/example/classfit/attendance/repository/AttendanceRepository.java
- src/main/java/classfit/example/classfit/attendance/service/AttendanceStatisticsService.java
- 구성원별 출결 통계 세부 정보 조회
- 날짜별 출결 통계 세부 정보 조회
- 날짜별 출결 통계 시 서브 클래스에 따른 출결 데이터 필터링 오류 해결
- AttendanceStatus에 '보강' 상태 추가할지 의논 필요
|기능|스크린샷|
|---|---|
|**구성원별 출결 통계 세부 정보 조회**|<img width="576" alt="image" src="https://github.com/user-attachments/assets/b3e4c693-1bff-4266-90c5-231d71b58af2">|
|**날짜별 출결 통계 세부 정보 조회**|<img width="579" alt="image" src="https://github.com/user-attachments/assets/a42ebc20-3ba9-4bd6-b9de-17920cc7ca16">|
Resolved: #90
> [Feat] 출결 통계 세부 정보 조회

- .github/workflows/gradle.yml
- .gitignore
- Dockerfile
- docker-compose.yml
- src/main/java/classfit/example/classfit/auth/security/config/SecurityConfig.java
- src/main/java/classfit/example/classfit/common/config/RedisConfig.java
- src/main/java/classfit/example/classfit/common/config/SwaggerController.java
- src/main/java/classfit/example/classfit/common/util/RedisUtil.java
* CI/CD 환경 설정 및 파이프라인 구축을 위한 작업 진행
---
1. 기존 EC2 Self Host Runner에서 Redis, MySQL, Spring 기반의 CI/CD 파이프라인 Docker Compose로 구성.
2. GitHub Actions를 활용한 파이프라인 구축.
---
- #114
---
- docker-compose.yml
- GitHub Actions Workflow 파일 (.github/workflows/build.yml, .github/workflows/deploy.yml 등)
---
> [CI/CD] Docker Compose 기반의 Git Action 파이프라인 구축

- .github/workflows/gradle.yml
* 중지 혹은 실행되고 있는 컨테이너에 대한 처리
---
1. 중지된 컨테이너가 존재하지 않을 경우에도 실행되도록 조정
=
---
- #124
---
- gradle.yml
---
> [refactor] workflow step 수정

- src/main/java/classfit/example/classfit/studentExam/domain/StudentExamScore.java
- src/main/java/classfit/example/classfit/studentExam/dto/request/UpdateStudentScoreRequest.java
* 
---
1.
2.
---
- Closes #134 
---
-
-
-
---
> [refactor] 성적관리 api 프론트 요구사항 수정

- .github/workflows/gradle.yml
- src/main/resources/logback-spring.xml
* RollingFileAppender를 사용하여 날짜 기반으로 로그 파일이 롤링되도록 설정
* EC2 서버에서 로그 파일이 기록되도록 Docker Volume을 마운트
---
1. Logback 파일 설정
- RollingFileAppender를 통해 날짜별 로그 파일 롤링 적용
2. CI/CD 파이프라인 수정
- EC2에서 Docker 컨테이너 실행 시 로그 파일 마운트를 위한 옵션 추가
---
- #147 
---
- logback-spring.xml
- .github/workflows/gradle.yml
---
> [Feat]  날짜 기반 로그 파일 롤링 구현

- .github/workflows/gradle.yml
- src/main/java/classfit/example/classfit/common/config/SwaggerController.java
*  배포 수정합니다
---
1.
2.
---
- Closes #
---
-
-
-
---
> [cicd] 배포 수정

- src/main/java/classfit/example/classfit/drive/controller/DriveFileController.java
- src/main/java/classfit/example/classfit/drive/controller/DriveGetController.java
- src/main/java/classfit/example/classfit/drive/service/DriveDownloadService.java
* 드라이브 다중 파일 다운로드 및 리팩토링
---
1. 컨트롤러 파일 분리
2. 다중 파일 다운로드 처리
---
- Closes #166 
---
- DriveFileController.java
- DriveGetController.java
- DriveDownloadService.java
---
> [Refactor] 드라이브 다중 파일 다운로드

- src/main/java/classfit/example/classfit/calendarCategory/domain/CategoryColor.java
- src/main/java/classfit/example/classfit/calendarCategory/dto/response/CalendarCategoryResponse.java
- src/main/java/classfit/example/classfit/event/controller/EventController.java
- src/main/java/classfit/example/classfit/event/domain/Event.java
- src/main/java/classfit/example/classfit/event/dto/request/EventDragUpdate.java
- src/main/java/classfit/example/classfit/event/repository/EventRepository.java
- src/main/java/classfit/example/classfit/event/service/EventService.java
* 일정관리 프론트 요구사항 반영
---
1. 컬러 코드 넣기
2. 드래그 & 드롭용 일정 날짜 변경 api
3. 월별 일정 조회를 캘린더 타입에 맞게 조회되도록 변경
---
- #162 
---
- CategoryColor.java
- CalendarCategoryResponse.java
- EventController.java
- Event.java
- EventDragUpdate.java
- EventRepository.java
- EventService.java
---
- 날짜 지정 하지 않을 경우 6개월까지 반복 처리
> [Refactor] 일정관리 프론트 요구사항 반영

- src/main/java/classfit/example/classfit/classStudent/repository/ClassStudentRepository.java
- src/main/java/classfit/example/classfit/scoreReport/domain/ScoreReport.java
- src/main/java/classfit/example/classfit/scoreReport/service/ScoreReportService.java
* 클래스별 학생 전체조회 api
* 학원별 학습리포트 전체조회 api 수정
---
1.
2.
---
- Closes #134 
---
-
-
-
---
> [fix] 학습리포트 쿼리 수정

- src/main/java/classfit/example/classfit/event/domain/Event.java
- src/main/java/classfit/example/classfit/event/service/EventCreateService.java
- src/main/java/classfit/example/classfit/event/service/EventGetService.java
- src/main/java/classfit/example/classfit/event/service/EventRepeatService.java
- src/main/java/classfit/example/classfit/event/service/EventService.java
- src/main/java/classfit/example/classfit/event/service/EventUpdateService.java
* 기능별 파일 분리 및 중복 제거
---
1. 중복 제거
2. 파일 분리
---
- #172 
---
- Event.java
- EventCreateService.java
- EventGetService.java
- EventRepeatService.java
- EventService.java
- EventUpdateService.java
---
> [Refactor] 일정관리 리팩토링

- src/main/java/classfit/example/classfit/auth/security/filter/CustomLoginFilter.java
- src/main/java/classfit/example/classfit/common/util/DriveUtil.java
- src/main/java/classfit/example/classfit/drive/controller/DriveFolderController.java
- src/main/java/classfit/example/classfit/drive/service/DriveFolderService.java
- src/main/java/classfit/example/classfit/drive/service/DriveTrashService.java
- 휴지통 이동 API 호출 시, 원본 폴더 사라지는 버그 수정
* 폴더 삭제 기능을 구현
*  하위 파일 존재 시, 휴지통으로 이동
---
1. 폴더 삭제 구현
- 폴더 하위 파일 존재 시, 휴지통으로 이동
---
- Closes #179 
---
- DriveFolderController
- DriveFolderService
- DriveTrashService
---
> [Feat] 드라이브 폴더 삭제 API 구현

- src/main/java/classfit/example/classfit/event/dto/response/EventMontylyResponse.java
- src/main/java/classfit/example/classfit/event/service/EventGetService.java
* 일정관리 프론트 요구사항 반영
---
1. 월별 일정 조회 시 카테고리 색상 추가
---
- Closes #182 
---
- EventMontylyResponse.java
- EventGetService.java
---
> [refactor] 월별 일정 조회 시 카테고리 색상 추가 #182

- src/main/java/classfit/example/classfit/drive/controller/DriveFileController.java
- src/main/java/classfit/example/classfit/drive/service/DriveDownloadService.java
* 드라이브 프론트 요구사항
---
1. 다운로드하는 파일명 이름 형식 수정
2. 다운로드 오류 해결 
---
- #176
---
- DriveFileController.java
- DriveDownloadService.java
---
ex) ita 폴더를 만들고 folderPath에 ita를 넣으면 ita 폴더가 나오는 문제
> [Refactor] 드라이브 프론트 요구사항

- src/main/java/classfit/example/classfit/scoreReport/controller/ScoreReportController.java
- src/main/java/classfit/example/classfit/scoreReport/service/ScoreReportService.java
* 학습리포트 전체조회 requestParam 삭제
---
1.
2.
---
- Closes #134
---
-
-
-
---
> [refactor] 학습리포트 전체조회 requestParam 삭제

- src/main/java/classfit/example/classfit/event/controller/EventController.java
- src/main/java/classfit/example/classfit/event/domain/Event.java
- src/main/java/classfit/example/classfit/event/dto/response/EventModalResponse.java
- src/main/java/classfit/example/classfit/event/service/EventGetService.java
- src/main/java/classfit/example/classfit/event/service/EventRepeatService.java
- src/main/java/classfit/example/classfit/event/service/EventService.java
* 프론트 일정관리 피드백 반영
---
1. 월별 일정 조회 필드 추가
2. 반복 일정 생성 오류 해결
---
- #182 
---
- EventController.java
- Event.java
- EventModalResponse.java
- EventGetService.java
- EventRepeatService.java
- EventService.java
---
> [Refactor] 일정관리 프론트

- src/main/java/classfit/example/classfit/drive/service/DriveFolderService.java
- src/main/java/classfit/example/classfit/drive/service/DriveGetService.java
- src/main/java/classfit/example/classfit/drive/service/DriveUploadService.java
* 드라이브 프론트 요구사항
* 폴더 조회 오류 해결
ex) ita 폴더를 만들고 folderPath에 ita를 넣으면 ita 폴더가 나오는 문제
---
1. 폴더 조회 오류 해결
2. 파일 검색 및 필터링 오류 해결
3. 빈 문자열 폴더 생성 방지
---
- #176 
---
- DriveFolderService.java
- DriveGetService.java
- DriveUploadService.java
---
> [Fix] 드라이브 프론트 요구사항

- src/main/java/classfit/example/classfit/category/controller/MainClassController.java
- src/main/java/classfit/example/classfit/category/dto/request/MainClassRequest.java
- src/main/java/classfit/example/classfit/category/service/MainClassService.java
* 메인 클래스 수정 API 수정 기능 구현
---
1. 유효성 검증 어노테이션 추가
2. 메인 클래스 이름 수정
---
- Closes #201 
---
- MainClassRequest
- MainClassController
- MainClassService
---
> [Feat] 메인 클래스 수정 API 구현

- src/main/java/classfit/example/classfit/common/util/DriveUtil.java
* 폴더 조회 오류 해결
ex) folderPath에 있는 폴더가 조회되지 않는 문제
---
1.  folderPath에 있는 폴더가 조회되지 않는 문제 해결
---
- #181
---
- DriveUtil.java
---
> [fix] 파일 조회 오류 해결 #181

- src/main/java/classfit/example/classfit/auth/security/filter/CustomLoginFilter.java
- src/main/java/classfit/example/classfit/category/controller/ClassInfoController.java
- src/main/java/classfit/example/classfit/category/repository/MainClassRepository.java
- src/main/java/classfit/example/classfit/category/service/ClassInfoService.java
- src/main/java/classfit/example/classfit/classStudent/repository/ClassStudentRepository.java
- src/main/java/classfit/example/classfit/student/repository/StudentRepository.java
- src/main/java/classfit/example/classfit/student/service/StudentService.java
- src/main/java/classfit/example/classfit/studentExam/service/ExamService.java
*  시험지 전체조회시 에러 수정
---
1. 시험지 전체조회시 에러 수정
---
- Closes #208 
---
- ExamService.java
---
> [fix] 시험지 전체조회시 에러 수정

- src/main/java/classfit/example/classfit/attendance/controller/AttendanceController.java
- src/main/java/classfit/example/classfit/attendance/controller/AttendanceExportController.java
- src/main/java/classfit/example/classfit/attendance/controller/AttendanceStatisticsController.java
- src/main/java/classfit/example/classfit/attendance/repository/AttendanceRepository.java
- src/main/java/classfit/example/classfit/attendance/service/AttendanceExportService.java
- src/main/java/classfit/example/classfit/attendance/service/AttendanceService.java
- src/main/java/classfit/example/classfit/attendance/service/AttendanceStatisticsService.java
- src/main/java/classfit/example/classfit/attendance/service/AttendanceUpdateService.java
- src/main/java/classfit/example/classfit/category/repository/MainClassRepository.java
- src/main/java/classfit/example/classfit/category/service/ClassInfoService.java
- src/main/java/classfit/example/classfit/classStudent/repository/ClassStudentRepository.java
- src/main/java/classfit/example/classfit/student/repository/StudentRepository.java
Reverts ITA-OneByte/OneByte-BE#219
> Revert "[Fix] 로그인한 멤버 데이터 조회"

- src/main/java/classfit/example/classfit/attendance/repository/AttendanceRepository.java
- src/main/java/classfit/example/classfit/category/repository/MainClassRepository.java
- src/main/java/classfit/example/classfit/classStudent/repository/ClassStudentRepository.java
- src/main/java/classfit/example/classfit/student/repository/StudentRepository.java
* conflict 해결
---
1. mainClass 엔티티 수정 반영
2. class-info 조회 conflict 해결
---
- Closes #177 
---
- AttendanceRepository.java
- MainClassRepository.java
- ClassStudentRepository.java
- StudentRepository.java
---
> [Fix] 출결 조회 conflict 해결

- src/main/java/classfit/example/classfit/attendance/repository/AttendanceRepository.java
- src/main/java/classfit/example/classfit/classStudent/repository/ClassStudentRepository.java
- src/main/java/classfit/example/classfit/student/repository/StudentRepository.java
Reverts ITA-OneByte/OneByte-BE#221
> Revert "[Fix] 출결 조회 conflict 해결"

- src/main/java/classfit/example/classfit/attendance/controller/AttendanceController.java
- src/main/java/classfit/example/classfit/attendance/controller/AttendanceExportController.java
- src/main/java/classfit/example/classfit/attendance/controller/AttendanceStatisticsController.java
- src/main/java/classfit/example/classfit/attendance/repository/AttendanceRepository.java
- src/main/java/classfit/example/classfit/attendance/service/AttendanceExportService.java
- src/main/java/classfit/example/classfit/attendance/service/AttendanceService.java
- src/main/java/classfit/example/classfit/attendance/service/AttendanceStatisticsService.java
- src/main/java/classfit/example/classfit/attendance/service/AttendanceUpdateService.java
- src/main/java/classfit/example/classfit/classStudent/repository/ClassStudentRepository.java
- src/main/java/classfit/example/classfit/student/repository/StudentRepository.java
* 출결 데이터 공용으로 조회되는 문제
---
1. 출결 관리 개인 조회로 변경
2. 클래스 정보가 학원 멤버에게만 조회되도록 변경
3. conflict 해결
---
- Closes #227
---
- AttendanceController.java
- AttendanceExportController.java
- AttendanceStatisticsController.java
- AttendanceRepository.java
- AttendanceExportService.java
- AttendanceService.java
- AttendanceStatisticsService.java
- AttendanceUpdateService.java
- ClassStudentRepository.java
- StudentRepository.java
---
> [Fix] 출결관리 관련 에러 수정

- src/main/java/classfit/example/classfit/scoreReport/service/ScoreReportService.java
- src/main/java/classfit/example/classfit/studentExam/domain/Exam.java
- src/main/java/classfit/example/classfit/studentExam/domain/ExamRepository.java
- src/main/java/classfit/example/classfit/studentExam/domain/StudentExamScore.java
- src/main/java/classfit/example/classfit/studentExam/domain/StudentExamScoreRepository.java
- src/main/java/classfit/example/classfit/studentExam/dto/process/ExamHistory.java
- src/main/java/classfit/example/classfit/studentExam/dto/request/FindExamRequest.java
- src/main/java/classfit/example/classfit/studentExam/dto/response/ShowExamDetailResponse.java
- src/main/java/classfit/example/classfit/studentExam/service/ExamService.java
* 성적관리 관련 에러 수정
---
1.시험 생성 후 시험 highestScore 수정 할 경우 모든 학생들의 점수는 0으로 초기화 되도록 수정
2.시험지 생성 후 새로운 학생이 추가됐을 때 학생 점수 수정 api에서 모두 수정 가능하도록 수정
3.학원 검증 메서드 수정
4.시험지 검색 시 mainClass,subClass 도 받도록 수정
5.평균 소수점 한자리까지 남겨놓도록 수정
---
- Closes #226
---
-
-
-
---
> [fix] 성적관리 관련 에러 수정

- src/main/java/classfit/example/classfit/student/controller/StudentController.java
* RequestParam name 추가 
---
1.RequestParam name 추가 
---
- Closes #225
---
-
-
-
---
> [refactor] RequestParam name 추가 

- src/main/java/classfit/example/classfit/student/service/StudentService.java
* 학생 등록 후 출결 조회 시 과거 데이터 부재
---
1. 학생 등록 시 출결 데이터 생성할 때 4주 전 데이터(결석 상태) 생성하기
---
- Closes #239 
---
- StudentService.java
---
> [Chore] 학생 클래스 등록 시 7주 출결 데이터 생성

- src/main/java/classfit/example/classfit/calendarCategory/repository/CalendarCategoryRepository.java
- src/main/java/classfit/example/classfit/calendarCategory/service/CalendarCategoryService.java
- src/main/java/classfit/example/classfit/event/repository/EventRepository.java
- src/main/java/classfit/example/classfit/event/service/EventGetService.java
* 일정 데이터 공용으로 조회되는 문제
---
1. 공유 캘린더 카테고리 조회되도록 하기
2. 공유 캘린더 일정 조회되도록 하기
---
- Closes #232 
---
- CalendarCategoryRepository.java
- CalendarCategoryService.java
- EventRepository.java
- EventGetService.java
---
> [Fix] 일정관련 관련 에러 수정

- src/main/java/classfit/example/classfit/classStudent/repository/ClassStudentRepository.java
- src/main/java/classfit/example/classfit/scoreReport/domain/ScoreReport.java
- src/main/java/classfit/example/classfit/studentExam/domain/Exam.java
- src/main/java/classfit/example/classfit/studentExam/domain/ExamRepository.java
- src/main/java/classfit/example/classfit/studentExam/dto/response/FindExamResponse.java
- src/main/java/classfit/example/classfit/studentExam/service/ExamService.java
* 
---
1.
2.
---
- Closes #
---
-
-
-
---
> [fix] 성적관리 2차 수정

- src/main/java/classfit/example/classfit/studentExam/domain/StudentExamScoreRepository.java
* 
---
1.
2.
---
- Closes #
---
-
-
-
---
> [fix] 다른 학원 조회못하도록 수정 #241

- src/main/java/classfit/example/classfit/common/util/DriveUtil.java
- src/main/java/classfit/example/classfit/drive/service/DriveGetService.java
- src/main/java/classfit/example/classfit/drive/service/DriveTrashService.java
- src/main/java/classfit/example/classfit/drive/service/DriveUploadService.java
* 하위 파일들의 크기의 합이 폴더 크기로 되게 설정
---
1. 하위 파일들의 크기의 합이 폴더 크기로 되게 설정
2. 파일 업로드 시간 한국 시간대로 변경
---
- Closes #243 
---
- DriveUtil.java
- DriveGetService.java
- DriveTrashService.java
- DriveUploadService.java
---
> [Fix] 드라이브 폴더 크기 변경

- src/main/java/classfit/example/classfit/scoreReport/domain/ScoreReport.java
- src/main/java/classfit/example/classfit/scoreReport/domain/ScoreReportRepository.java
- src/main/java/classfit/example/classfit/scoreReport/dto/request/CreateReportRequest.java
- src/main/java/classfit/example/classfit/scoreReport/dto/response/CreateReportResponse.java
- src/main/java/classfit/example/classfit/scoreReport/dto/response/FindAllReportResponse.java
- src/main/java/classfit/example/classfit/scoreReport/dto/response/FindReportResponse.java
- src/main/java/classfit/example/classfit/scoreReport/service/ScoreReportService.java
* 
---
1.
2.
---
- Closes #
---
-
-
-
---
> [fix] 학습리포트 작성자 추가 

- src/main/java/classfit/example/classfit/common/util/DriveUtil.java
- src/main/java/classfit/example/classfit/drive/service/DriveGetService.java
- src/main/java/classfit/example/classfit/drive/service/DriveTrashService.java
- src/main/java/classfit/example/classfit/drive/service/DriveUploadService.java
Reverts ITA-OneByte/OneByte-BE#249
> Revert "[Release] 배포"

- src/main/java/classfit/example/classfit/attendance/domain/Attendance.java
- src/main/java/classfit/example/classfit/attendance/repository/AttendanceRepository.java
- src/main/java/classfit/example/classfit/attendance/service/AttendanceExportService.java
- src/main/java/classfit/example/classfit/attendance/service/AttendanceSchedulingService.java
- src/main/java/classfit/example/classfit/attendance/service/AttendanceService.java
- src/main/java/classfit/example/classfit/attendance/service/AttendanceStatisticsService.java
- src/main/java/classfit/example/classfit/classStudent/repository/ClassStudentRepository.java
- src/main/java/classfit/example/classfit/scoreReport/domain/ScoreReportRepository.java
- src/main/java/classfit/example/classfit/scoreReport/service/ScoreReportService.java
- src/main/java/classfit/example/classfit/student/controller/StudentController.java
- src/main/java/classfit/example/classfit/student/domain/Student.java
- src/main/java/classfit/example/classfit/student/service/StudentService.java
- src/main/java/classfit/example/classfit/studentExam/domain/StudentExamScoreRepository.java
* 학생 엔티티에 출결 정보가 존재하여 발생하는 의존성 문제 해결
---
1. Student에서 attendances 필드 삭제
2. Attendance에서 student 필드 삭제
3. 관련 코드 수정
4. 학생 삭제 오류 해결
---
- Closes #230 
---
- Attendance.java
- AttendanceRepository.java
- AttendanceExportService.java
- AttendanceSchedulingService.java
- AttendanceService.java
- AttendanceStatisticsService.java
- ScoreReportService.java
- Student.java
- StudentService.java
---
> [Fix] 학생 삭제

- src/main/java/classfit/example/classfit/auth/filter/JWTFilter.java
- src/main/java/classfit/example/classfit/common/config/AsyncConfig.java
- src/main/java/classfit/example/classfit/mail/service/EmailAsyncService.java
- src/main/java/classfit/example/classfit/mail/service/EmailService.java
* 이메일 전송 API 호출 후 응답 시간이 지연되는 문제를 개선하기 위해 비동기(멀티스레드) 방식으로 리팩토링 진행.
---
1. 비동기 처리를 위해 이메일 전송 메서드에 `@Async` 어노테이션 적용
2. 효율적인 동시 처리를 위해 `ThreadPoolTaskExecutor`를 활용하여 스레드 풀 설정
3. `CompletableFuture`를 사용하여 클라이언트가 기다리지 않고 응답을 받을 수 있도록 개선
---
- Closes #272 
---
- `AsyncConfig.java`
- `EmailService.java`
---
> [Refactor] @Async를 통한 이메일 인증 기능 비동기 처리

- gradle/wrapper/gradle-wrapper.properties
- src/main/java/classfit/example/classfit/common/util/DriveUtil.java
- src/main/java/classfit/example/classfit/drive/domain/Drive.java
- src/main/java/classfit/example/classfit/drive/repository/DriveRepository.java
- src/main/java/classfit/example/classfit/student/dto/request/StudentUpdateRequest.java
- src/main/java/classfit/example/classfit/student/service/StudentService.java
- src/test/java/classfit/example/classfit/academy/service/AcademyCreateServiceTest.java
- src/test/java/classfit/example/classfit/academy/service/AcademyJoinServiceTest.java
- src/test/java/classfit/example/classfit/drive/service/DriveDeleteServiceTest.java
- src/test/java/classfit/example/classfit/drive/service/DriveDownloadServiceTest.java
- src/test/java/classfit/example/classfit/drive/service/DriveGetServiceTest.java
- src/test/java/classfit/example/classfit/drive/service/DriveRestoreServiceTest.java
- src/test/java/classfit/example/classfit/drive/service/DriveTrashServiceTest.java
- src/test/java/classfit/example/classfit/drive/service/DriveUploadServiceTest.java
- src/test/java/classfit/example/classfit/invitation/service/InvitationServiceTest.java
- src/test/java/classfit/example/classfit/mail/service/EmailServiceTest.java
- src/test/java/classfit/example/classfit/member/service/MemberServiceTest.java
- src/test/java/classfit/example/classfit/student/service/StudentCreateServiceTest.java
- src/test/java/classfit/example/classfit/student/service/StudentDeleteServiceTest.java
- src/test/java/classfit/example/classfit/student/service/StudentQueryServiceTest.java
* 주요 로직에 대한 단위 테스트 코드 작성
---
1. 학원 관련 API 테스트 코드 작성
2. 드라이브 관련 API 테스트 코드 작성
3. 회원 관련 API 테스트 코드 작성
4. 이메일 전송 API 테스트 코드 작성
5. 학생 관련 API 테스트 코드 작성
---
- Closes #279
---
> [Test] 주요 로직 테스트 코드 작성
